services:
    runroom.redirection.admin.redirect:
        class: Runroom\RedirectionBundle\Admin\RedirectAdmin
        public: true
        arguments: [~, Runroom\RedirectionBundle\Entity\Redirect, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Redirects' }
